# Generated by Django 3.2.2 on 2021-05-06 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='Название ингредиента')),
                ('manufacture_date', models.DateField(verbose_name='Дата изготовлеиня')),
                ('sell_by', models.DateField(verbose_name='Годен до')),
                ('calories', models.IntegerField(verbose_name='Количество калорий')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Reciepes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='Название рецепта')),
                ('description', models.TextField(verbose_name='Описание рецепта')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.TextField(verbose_name='Название производителя')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredients', verbose_name='Ингредиенты')),
            ],
        ),
    ]
