# Generated by Django 3.2.2 on 2021-05-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='price',
            field=models.IntegerField(verbose_name='Цена за 1кг'),
        ),
    ]
