# Generated by Django 3.2.2 on 2021-05-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210506_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ингредиенты', to='main.ingredients', verbose_name='Производит'),
        ),
    ]
