# Generated by Django 3.2.2 on 2021-05-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_manufacturer_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата поставки')),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50, verbose_name='Город откуда поставляют')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.RenameModel(
            old_name='Manufacturer',
            new_name='Manufacturers',
        ),
        migrations.CreateModel(
            name='ProviderIngredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredients', verbose_name='Ингредиент')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.providers', verbose_name='Поставщик')),
            ],
        ),
    ]
