# Generated by Django 3.2.2 on 2021-05-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210506_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveries',
            options={'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
        migrations.AlterModelOptions(
            name='provideringredients',
            options={'verbose_name': 'Ингредиент поставщика', 'verbose_name_plural': 'Ингредиенты поставщиков'},
        ),
        migrations.AddField(
            model_name='deliveries',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ingredients', verbose_name='Ингредиент'),
            preserve_default=False,
        ),
    ]
