# Generated by Django 3.2.2 on 2021-05-06 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210506_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciepes',
            name='ingredient',
            field=models.ManyToManyField(to='main.Ingredients', verbose_name='Ингредиенты'),
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Название блюда')),
                ('manufacture_date', models.DateField(verbose_name='Дата изготовлеиня')),
                ('sell_by', models.DateField(verbose_name='Годен до')),
                ('reciepe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reciepes', verbose_name='Рецепт')),
            ],
        ),
    ]
