# Generated by Django 3.2.2 on 2021-05-06 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210507_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='since',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата основания'),
            preserve_default=False,
        ),
    ]
