# Generated by Django 3.2.2 on 2021-05-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_deliveries_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='city',
            field=models.TextField(default=1, verbose_name='Город поставки'),
            preserve_default=False,
        ),
    ]
