# Generated by Django 3.2.2 on 2021-05-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_deliveries_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishesphoto',
            name='dishe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.dishes'),
        ),
    ]
