# Generated by Django 3.2.2 on 2021-05-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_dishesphoto_dishe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reciepes',
            new_name='Recipes',
        ),
        migrations.RenameField(
            model_name='dishes',
            old_name='reciepe',
            new_name='recipe',
        ),
    ]
